declare module "monday-ui-react-core" {
  export const Tooltip: any;
  export const Dropdown: any;
  export const Button: any;
  export const Icon: any;
  export const Modal: any;
  export const ModalContent: any;
  export const Steps: any;
  export const TextField: any;
  export const TextArea: any;
  export const Toggle: any;
  export const Table: any;
  export const TableHeader: any;
  export const TableHeaderCell: any;
  export const TableBody: any;
  export const TableRow: any;
  export const TableCell: any;
  export const Label: any;
  export const Tab: any;
  export const TabList: any;
  export const LinearProgressBar: any;
}
